// Generated by gencpp from file bb8_move_class_custom/BB8MoveServiceMessage.msg
// DO NOT EDIT!


#ifndef BB8_MOVE_CLASS_CUSTOM_MESSAGE_BB8MOVESERVICEMESSAGE_H
#define BB8_MOVE_CLASS_CUSTOM_MESSAGE_BB8MOVESERVICEMESSAGE_H

#include <ros/service_traits.h>


#include <bb8_move_class_custom/BB8MoveServiceMessageRequest.h>
#include <bb8_move_class_custom/BB8MoveServiceMessageResponse.h>


namespace bb8_move_class_custom
{

struct BB8MoveServiceMessage
{

typedef BB8MoveServiceMessageRequest Request;
typedef BB8MoveServiceMessageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BB8MoveServiceMessage
} // namespace bb8_move_class_custom


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bb8_move_class_custom::BB8MoveServiceMessage > {
  static const char* value()
  {
    return "b92c952a9248b3029cefe45f52f6ffde";
  }

  static const char* value(const ::bb8_move_class_custom::BB8MoveServiceMessage&) { return value(); }
};

template<>
struct DataType< ::bb8_move_class_custom::BB8MoveServiceMessage > {
  static const char* value()
  {
    return "bb8_move_class_custom/BB8MoveServiceMessage";
  }

  static const char* value(const ::bb8_move_class_custom::BB8MoveServiceMessage&) { return value(); }
};


// service_traits::MD5Sum< ::bb8_move_class_custom::BB8MoveServiceMessageRequest> should match
// service_traits::MD5Sum< ::bb8_move_class_custom::BB8MoveServiceMessage >
template<>
struct MD5Sum< ::bb8_move_class_custom::BB8MoveServiceMessageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bb8_move_class_custom::BB8MoveServiceMessage >::value();
  }
  static const char* value(const ::bb8_move_class_custom::BB8MoveServiceMessageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bb8_move_class_custom::BB8MoveServiceMessageRequest> should match
// service_traits::DataType< ::bb8_move_class_custom::BB8MoveServiceMessage >
template<>
struct DataType< ::bb8_move_class_custom::BB8MoveServiceMessageRequest>
{
  static const char* value()
  {
    return DataType< ::bb8_move_class_custom::BB8MoveServiceMessage >::value();
  }
  static const char* value(const ::bb8_move_class_custom::BB8MoveServiceMessageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bb8_move_class_custom::BB8MoveServiceMessageResponse> should match
// service_traits::MD5Sum< ::bb8_move_class_custom::BB8MoveServiceMessage >
template<>
struct MD5Sum< ::bb8_move_class_custom::BB8MoveServiceMessageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bb8_move_class_custom::BB8MoveServiceMessage >::value();
  }
  static const char* value(const ::bb8_move_class_custom::BB8MoveServiceMessageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bb8_move_class_custom::BB8MoveServiceMessageResponse> should match
// service_traits::DataType< ::bb8_move_class_custom::BB8MoveServiceMessage >
template<>
struct DataType< ::bb8_move_class_custom::BB8MoveServiceMessageResponse>
{
  static const char* value()
  {
    return DataType< ::bb8_move_class_custom::BB8MoveServiceMessage >::value();
  }
  static const char* value(const ::bb8_move_class_custom::BB8MoveServiceMessageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BB8_MOVE_CLASS_CUSTOM_MESSAGE_BB8MOVESERVICEMESSAGE_H
