// Generated by gencpp from file move_bb8_in_circle_custom/MoveBB8Custom.msg
// DO NOT EDIT!


#ifndef MOVE_BB8_IN_CIRCLE_CUSTOM_MESSAGE_MOVEBB8CUSTOM_H
#define MOVE_BB8_IN_CIRCLE_CUSTOM_MESSAGE_MOVEBB8CUSTOM_H

#include <ros/service_traits.h>


#include <move_bb8_in_circle_custom/MoveBB8CustomRequest.h>
#include <move_bb8_in_circle_custom/MoveBB8CustomResponse.h>


namespace move_bb8_in_circle_custom
{

struct MoveBB8Custom
{

typedef MoveBB8CustomRequest Request;
typedef MoveBB8CustomResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveBB8Custom
} // namespace move_bb8_in_circle_custom


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::move_bb8_in_circle_custom::MoveBB8Custom > {
  static const char* value()
  {
    return "b92c952a9248b3029cefe45f52f6ffde";
  }

  static const char* value(const ::move_bb8_in_circle_custom::MoveBB8Custom&) { return value(); }
};

template<>
struct DataType< ::move_bb8_in_circle_custom::MoveBB8Custom > {
  static const char* value()
  {
    return "move_bb8_in_circle_custom/MoveBB8Custom";
  }

  static const char* value(const ::move_bb8_in_circle_custom::MoveBB8Custom&) { return value(); }
};


// service_traits::MD5Sum< ::move_bb8_in_circle_custom::MoveBB8CustomRequest> should match
// service_traits::MD5Sum< ::move_bb8_in_circle_custom::MoveBB8Custom >
template<>
struct MD5Sum< ::move_bb8_in_circle_custom::MoveBB8CustomRequest>
{
  static const char* value()
  {
    return MD5Sum< ::move_bb8_in_circle_custom::MoveBB8Custom >::value();
  }
  static const char* value(const ::move_bb8_in_circle_custom::MoveBB8CustomRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_bb8_in_circle_custom::MoveBB8CustomRequest> should match
// service_traits::DataType< ::move_bb8_in_circle_custom::MoveBB8Custom >
template<>
struct DataType< ::move_bb8_in_circle_custom::MoveBB8CustomRequest>
{
  static const char* value()
  {
    return DataType< ::move_bb8_in_circle_custom::MoveBB8Custom >::value();
  }
  static const char* value(const ::move_bb8_in_circle_custom::MoveBB8CustomRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::move_bb8_in_circle_custom::MoveBB8CustomResponse> should match
// service_traits::MD5Sum< ::move_bb8_in_circle_custom::MoveBB8Custom >
template<>
struct MD5Sum< ::move_bb8_in_circle_custom::MoveBB8CustomResponse>
{
  static const char* value()
  {
    return MD5Sum< ::move_bb8_in_circle_custom::MoveBB8Custom >::value();
  }
  static const char* value(const ::move_bb8_in_circle_custom::MoveBB8CustomResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_bb8_in_circle_custom::MoveBB8CustomResponse> should match
// service_traits::DataType< ::move_bb8_in_circle_custom::MoveBB8Custom >
template<>
struct DataType< ::move_bb8_in_circle_custom::MoveBB8CustomResponse>
{
  static const char* value()
  {
    return DataType< ::move_bb8_in_circle_custom::MoveBB8Custom >::value();
  }
  static const char* value(const ::move_bb8_in_circle_custom::MoveBB8CustomResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVE_BB8_IN_CIRCLE_CUSTOM_MESSAGE_MOVEBB8CUSTOM_H
