// Generated by gencpp from file move_bb8_in_circle_custom/MoveBB8CustomRequest.msg
// DO NOT EDIT!


#ifndef MOVE_BB8_IN_CIRCLE_CUSTOM_MESSAGE_MOVEBB8CUSTOMREQUEST_H
#define MOVE_BB8_IN_CIRCLE_CUSTOM_MESSAGE_MOVEBB8CUSTOMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_bb8_in_circle_custom
{
template <class ContainerAllocator>
struct MoveBB8CustomRequest_
{
  typedef MoveBB8CustomRequest_<ContainerAllocator> Type;

  MoveBB8CustomRequest_()
    : duration(0)  {
    }
  MoveBB8CustomRequest_(const ContainerAllocator& _alloc)
    : duration(0)  {
  (void)_alloc;
    }



   typedef int32_t _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::move_bb8_in_circle_custom::MoveBB8CustomRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_bb8_in_circle_custom::MoveBB8CustomRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveBB8CustomRequest_

typedef ::move_bb8_in_circle_custom::MoveBB8CustomRequest_<std::allocator<void> > MoveBB8CustomRequest;

typedef boost::shared_ptr< ::move_bb8_in_circle_custom::MoveBB8CustomRequest > MoveBB8CustomRequestPtr;
typedef boost::shared_ptr< ::move_bb8_in_circle_custom::MoveBB8CustomRequest const> MoveBB8CustomRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_bb8_in_circle_custom::MoveBB8CustomRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_bb8_in_circle_custom::MoveBB8CustomRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::move_bb8_in_circle_custom::MoveBB8CustomRequest_<ContainerAllocator1> & lhs, const ::move_bb8_in_circle_custom::MoveBB8CustomRequest_<ContainerAllocator2> & rhs)
{
  return lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::move_bb8_in_circle_custom::MoveBB8CustomRequest_<ContainerAllocator1> & lhs, const ::move_bb8_in_circle_custom::MoveBB8CustomRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace move_bb8_in_circle_custom

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::move_bb8_in_circle_custom::MoveBB8CustomRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_bb8_in_circle_custom::MoveBB8CustomRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_bb8_in_circle_custom::MoveBB8CustomRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_bb8_in_circle_custom::MoveBB8CustomRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_bb8_in_circle_custom::MoveBB8CustomRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_bb8_in_circle_custom::MoveBB8CustomRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_bb8_in_circle_custom::MoveBB8CustomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1f60182c6a4cf2e688b1837c24d5f12e";
  }

  static const char* value(const ::move_bb8_in_circle_custom::MoveBB8CustomRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1f60182c6a4cf2e6ULL;
  static const uint64_t static_value2 = 0x88b1837c24d5f12eULL;
};

template<class ContainerAllocator>
struct DataType< ::move_bb8_in_circle_custom::MoveBB8CustomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_bb8_in_circle_custom/MoveBB8CustomRequest";
  }

  static const char* value(const ::move_bb8_in_circle_custom::MoveBB8CustomRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_bb8_in_circle_custom::MoveBB8CustomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 duration    # The time (in seconds) during which BB-8 will keep moving in circles\n"
;
  }

  static const char* value(const ::move_bb8_in_circle_custom::MoveBB8CustomRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_bb8_in_circle_custom::MoveBB8CustomRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveBB8CustomRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_bb8_in_circle_custom::MoveBB8CustomRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_bb8_in_circle_custom::MoveBB8CustomRequest_<ContainerAllocator>& v)
  {
    s << indent << "duration: ";
    Printer<int32_t>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_BB8_IN_CIRCLE_CUSTOM_MESSAGE_MOVEBB8CUSTOMREQUEST_H
