// Generated by gencpp from file move_bb8_in_circle_custom/MoveBB8CustomResponse.msg
// DO NOT EDIT!


#ifndef MOVE_BB8_IN_CIRCLE_CUSTOM_MESSAGE_MOVEBB8CUSTOMRESPONSE_H
#define MOVE_BB8_IN_CIRCLE_CUSTOM_MESSAGE_MOVEBB8CUSTOMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_bb8_in_circle_custom
{
template <class ContainerAllocator>
struct MoveBB8CustomResponse_
{
  typedef MoveBB8CustomResponse_<ContainerAllocator> Type;

  MoveBB8CustomResponse_()
    : success(false)  {
    }
  MoveBB8CustomResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::move_bb8_in_circle_custom::MoveBB8CustomResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_bb8_in_circle_custom::MoveBB8CustomResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveBB8CustomResponse_

typedef ::move_bb8_in_circle_custom::MoveBB8CustomResponse_<std::allocator<void> > MoveBB8CustomResponse;

typedef boost::shared_ptr< ::move_bb8_in_circle_custom::MoveBB8CustomResponse > MoveBB8CustomResponsePtr;
typedef boost::shared_ptr< ::move_bb8_in_circle_custom::MoveBB8CustomResponse const> MoveBB8CustomResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_bb8_in_circle_custom::MoveBB8CustomResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_bb8_in_circle_custom::MoveBB8CustomResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::move_bb8_in_circle_custom::MoveBB8CustomResponse_<ContainerAllocator1> & lhs, const ::move_bb8_in_circle_custom::MoveBB8CustomResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::move_bb8_in_circle_custom::MoveBB8CustomResponse_<ContainerAllocator1> & lhs, const ::move_bb8_in_circle_custom::MoveBB8CustomResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace move_bb8_in_circle_custom

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::move_bb8_in_circle_custom::MoveBB8CustomResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_bb8_in_circle_custom::MoveBB8CustomResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_bb8_in_circle_custom::MoveBB8CustomResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_bb8_in_circle_custom::MoveBB8CustomResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_bb8_in_circle_custom::MoveBB8CustomResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_bb8_in_circle_custom::MoveBB8CustomResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_bb8_in_circle_custom::MoveBB8CustomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::move_bb8_in_circle_custom::MoveBB8CustomResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::move_bb8_in_circle_custom::MoveBB8CustomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_bb8_in_circle_custom/MoveBB8CustomResponse";
  }

  static const char* value(const ::move_bb8_in_circle_custom::MoveBB8CustomResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_bb8_in_circle_custom::MoveBB8CustomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success      # Did it achieve it?\n"
;
  }

  static const char* value(const ::move_bb8_in_circle_custom::MoveBB8CustomResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_bb8_in_circle_custom::MoveBB8CustomResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveBB8CustomResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_bb8_in_circle_custom::MoveBB8CustomResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_bb8_in_circle_custom::MoveBB8CustomResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_BB8_IN_CIRCLE_CUSTOM_MESSAGE_MOVEBB8CUSTOMRESPONSE_H
