(cl:defpackage bb8_move_class_custom-srv
  (:use )
  (:export
   "BB8MOVESERVICEMESSAGE"
   "<BB8MOVESERVICEMESSAGE-REQUEST>"
   "BB8MOVESERVICEMESSAGE-REQUEST"
   "<BB8MOVESERVICEMESSAGE-RESPONSE>"
   "BB8MOVESERVICEMESSAGE-RESPONSE"
  ))

